### PR TITLE
Provide the local ip address by default

### PR DESCRIPTION
**Pull request by ZeusTheTrueGod**
The babel plugin detects the current ip address and then uses it by default in ip address settings.

Babel plugin is here https://github.com/ZeusTheTrueGod/babel-plugin-ip-address/ with the primitive
https://github.com/ZeusTheTrueGod/babel-plugin-ip-address/blob/master/index.js

### CODE REVIEW

**Comment by christocracy** [comment]
```
React packager ready.

Loading dependency graph, done.
error: bundling: TypeError: Cannot read property 'mac' of undefined
    at Object.<anonymous> (/Users/chris/Documents/workspace/react/background-geolocation/tmp/rn-background-geolocation-demo/node_modules/babel-plugin-ip-address/index.js:5:84)
    at Module._compile (module.js:570:32)
    at Module._extensions..js (module.js:579:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/chris/Documents/workspace/react/background-geolocation/tmp/rn-background-geolocation-demo/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
TransformError: /Users/chris/Documents/workspace/react/background-geolocation/tmp/rn-background-geolocation-demo/index.ios.js: Cannot read property 'mac' of undefined
Bundling `index.ios.js`  0.0% (0/1), failed.
```

**Comment by christocracy** [comment]
`babel-plugin-ip-address`

Huh?
```
const macAddress = _.find(_.flatten(_.values(ifaces)), { address : '192.168.1.39'}).mac;
```

**Comment by ZeusTheTrueGod** [comment]
Have I hardcoded it? oh no.

**Comment by ZeusTheTrueGod** [comment]
Fixed!

**Comment by ZeusTheTrueGod** [comment]
please run `npm install` to fetch a latest version

**Comment by christocracy** [comment]
merged to master

**Pull request merged**
